### ISSUE TITLE
Call to a member function getRequest() on null

### ISSUE THREAD

**Issue by typo3ua** [smichaelsen/fluid-viewhelper-timespan#1]
Hello!

I try to use your `ViewHelper` but I ger error

`$this->arguments['extensionName'] = $this->arguments['extensionName'] ?: $this->controllerContext->getRequest()->getControllerExtensionName();`

I use TYPO3 9.5.11
PHP 7.2

**Comment by smichaelsen** [comment]
Thanks for you report. What exactly is the error message?

**Comment by typo3ua** [comment]
I add `{user.crdate -> vhts:timeSpan(limitUnits:'2')}`

But I see on the page  

`Call to a member function getRequest() on null`

![Call to a member function getRequest on null](https://user-images.githubusercontent.com/638022/69157305-6e2a1500-0aed-11ea-90a8-e4a23ca48c62.png)

**Comment by smichaelsen** [comment]
Thank you. I guess that means that the ViewHelper is currently not compatible with TYPO3 v9.

**Comment by typo3ua** [comment]
I need your help .. can you help me?

**Comment by smichaelsen** [comment]
As a workaround try to explicitly set the `extensionName` parameter.

**Comment by typo3ua** [comment]
Yes, it helped me ... thank you so much... have a nice evening
